### ISSUE TITLE
Plus symbol overlapping with heading

### ISSUE THREAD

**Issue by PawanKolhe** [cant89/gianni-accordion-js#2]
h1 tag overlapping with plus symbol:
![pr1](https://user-images.githubusercontent.com/8324407/71530473-f206c680-290f-11ea-9549-a82085868bfa.PNG)

Can be fixed by having a padding of 70px to the right:
- padding: 20px 70px 20px 30px;

![pr1_2](https://user-images.githubusercontent.com/8324407/71530479-f4692080-290f-11ea-8e3f-742f8af34d7c.PNG)

**Comment by cant89** [comment]
Hello @PawanKolhe , sorry for delay, I had missed it. Thank you for it, I've fixed it.
As a side note, consider that the CSS is not part of the library itself (except the small snippet shown in the readme), you can build your own one. The CSS in the Codepen is there only for the purpose of a demo.
